### ISSUE TITLE
自動中文翻譯模組-安裝失敗

### ISSUE THREAD

**Issue by viktor-snow** [RPMTW/ResourcePack-Mod-zh_tw#100]
我把東西放進資料夾後，發現資源包中無論如何都沒顯示，試了超多次。(版本也是對的)
看別人的影片好像是壓縮檔，但下載後我的是jar檔案。

**Comment by SiongSng** [comment]
是jar檔案沒有錯，詳細請直接到我們的官方Discord詢問 https://discord.gg/5xApZtgV2u
